{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.metamaps.positioning",
    "module": "metamap-positioning-core",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-core-0.3.0.jar",
          "url": "metamap-positioning-core-0.3.0.jar",
          "size": 157051,
          "sha512": "79eb448e0b12fa038ff05071e29caa593437fa2d9a64394171d1ca0158bf71d178d3391d96766a432a5f2f94aeab8ac0d8afce24b1062036c268276c8a745f03",
          "sha256": "740ae581bb5110e2aaa9ad76681ac8da18e3e15d25ce77cb0d397c69191a458a",
          "sha1": "04949240a119eab114855d9491127d3afd44173b",
          "md5": "986c74036c393eec7360423604eafa73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "metamap-positioning-core-0.3.0.jar",
          "url": "metamap-positioning-core-0.3.0.jar",
          "size": 157051,
          "sha512": "79eb448e0b12fa038ff05071e29caa593437fa2d9a64394171d1ca0158bf71d178d3391d96766a432a5f2f94aeab8ac0d8afce24b1062036c268276c8a745f03",
          "sha256": "740ae581bb5110e2aaa9ad76681ac8da18e3e15d25ce77cb0d397c69191a458a",
          "sha1": "04949240a119eab114855d9491127d3afd44173b",
          "md5": "986c74036c393eec7360423604eafa73"
        }
      ]
    }
  ]
}
