ext.postBuildExtras = {
    allprojects {
        repositories {
            google()
            mavenCentral()
            maven {
                url = uri(rootDir.resolve("app/src/main/java/libs/maven-repository"))
            }
        }
    }

    dependencies {
        val metamapVersion = rootDir.resolve("app/src/main/java/libs/VERSION").readText().trim()
        implementation("jp.metamaps.positioning:metamap-mapview:$metamapVersion")
    }
}