ext.postBuildExtras = {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri(rootDir.resolve("libs/maven-repository"))
        }
    }

    dependencies {
        implementation("jp.metamaps.positioning:metamap-mapview:0.3.0")
    }
}