plugins {
    id("com.android.application") version "9.3.1" apply false
    id("org.jetbrains.kotlin.android") version "2.4.10" apply false
}

dependencyResolutionManagement {
    repositories {
        maven {
            url = uri(rootDir.resolve("metamap/maven-repository"))
        }
    }
}

dependencies {
    val metamapVersion = rootDir.resolve("metamap/VERSION").readText().trim()
    implementation("jp.metamaps.positioning:metamap-mapview:$metamapVersion")
}